services:

  db:
    image: postgis/postgis:16-3.4
    container_name: seasentry-db

    env_file:
        - .env.docker

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

    restart: unless-stopped

  backend:
    build:
      context: ./backend

    container_name: seasentry-backend

    env_file:
      - .env.docker

    ports:
      - "5000:5000"

    depends_on:
      db:
        condition: service_healthy

    volumes:
      - ./backend:/app

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend

    container_name: seasentry-frontend

    ports:
      - "3000:3000"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    depends_on:
      - backend

    restart: no
  
  freetakserver:
    image: ghcr.io/freetakteam/freetakserver:latest
    container_name: seasentry-freetakserver
    restart: unless-stopped


    ports:
      - "8087:8087"
      - "8089:8089"
      - "8080:8080"
      - "8443:8443"
      - "19023:19023"

    environment:
      FTS_DATABASE_TYPE: SQLite
      FTS_CONNECTION_MESSAGE: "Connected to SeaSentry ATAK-CIV Integration test server. QOTD: At the end of the day, the day ends."
    
    volumes:
      - fts_data:/opt/fts

  freetakserver-ui:
    image: ghcr.io/freetakteam/ui:latest
    container_name: seasentry-freetakserver-ui
    restart: unless-stopped
    depends_on:
      - freetakserver
    ports:
      - "8000:8000"
    environment:
      APIIP: seasentry-freetakserver 
      APIPORT: 19023
      APIPROTOCOL: http
    volumes:
      - fts_data:/data/

volumes:
  postgres_data:
  fts_data: