[pytest]
pythonpath = .
markers =
    live: test will request from external site. `-m "not live"` to deselect
    ingestchain: tests for data ingestion pipeline (validation, normalisation, DB insertion).