# backend/app/modules/alerts/routes.py
# for api routes relating to alert queries

from flask import Blueprint, request, jsonify
import json
import threading
from datetime import datetime
from app.core.config import Settings
from app.modules.alerts.custom_rules import RuleTreeAdapter, build_sqlalchemy_expression 
from app.modules.alerts.engine import check_all_vessels

from app.utils.audit_log_helpers import write_audit_log
from app.utils.alert_helpers import (
    get_all_alert_history, get_all_alert_rule, get_alert_rule_by_id,
    update_alert_rule_in_db,
    mark_alert_as_read, mark_alert_as_unread,
    mark_rule_as_disable, mark_rule_as_enable,
    add_alert_rule_to_db,
    delete_alert_rule_in_db
    )

import logging

logger = logging.getLogger(__name__)
alerts_bp = Blueprint('alerts', __name__, url_prefix='/api/v1/alerts')

@alerts_bp.route('/history/all', methods=['GET'])
def get_all_alert_history_web():
    '''
    GET /api/v1/alerts/history/all
    Returns history of all alerts, both read and unread.
    
    Query Parameters (all optional):
    - start_time: ISO format datetime string (e.g., 2023-10-27T10:00:00)
    - end_time: ISO format datetime string (e.g., 2023-10-28T10:00:00)
    - limit: integer, max number of records to return (e.g., 50)
    - offset: integer, number of records to skip for pagination (e.g., 0)
    - by_alert_rule_id: integer, filters for history generated by alert rule with given id (e.g., 21)
    '''
    try:
        start_time_str = request.args.get('start_time')
        end_time_str = request.args.get('end_time')
        limit_str = request.args.get('limit')
        offset_str = request.args.get('offset')
        by_alert_rule_id_str = request.args.get('by_alert_rule_id')

        start_time = None
        end_time = None
        limit = None
        offset = None
        by_alert_rule_id = None

        if start_time_str:
            try:
                start_time = datetime.fromisoformat(start_time_str)
            except ValueError:
                return jsonify({"status": "error", "error": "Invalid start_time format. Use ISO format (e.g., 2023-10-27T10:00:00)"}), 400

        if end_time_str:
            try:
                end_time = datetime.fromisoformat(end_time_str)
            except ValueError:
                return jsonify({"status": "error", "error": "Invalid end_time format. Use ISO format (e.g., 2023-10-27T10:00:00)"}), 400

        if limit_str:
            try:
                limit = int(limit_str)
                if limit < 1:
                    return jsonify({"status": "error", "error": "Limit must be a positive integer"}), 400
            except ValueError:
                return jsonify({"status": "error", "error": "Invalid limit format. Must be an integer"}), 400

        if offset_str:
            try:
                offset = int(offset_str)
                if offset < 0:
                    return jsonify({"status": "error", "error": "Offset must be a non-negative integer"}), 400
            except ValueError:
                return jsonify({"status": "error", "error": "Invalid offset format. Must be an integer"}), 400

        if by_alert_rule_id_str:
            try:
                by_alert_rule_id = int(by_alert_rule_id_str)
                if by_alert_rule_id < 0:
                    return jsonify({"status": "error", "error": "by_alert_rule_id must be a non-negative integer"}), 400
            except ValueError:
                return jsonify({"status": "error", "error": "Invalid by_alert_rule_id format. Must be an integer"}), 400

        results = get_all_alert_history(start_time=start_time, end_time=end_time,
                                        limit=limit, offset=offset, by_alert_rule_id=by_alert_rule_id)

        data = []
        for alert in results:
            data.append({
                "alert_history_id": alert.alert_history_id,
                "alert_history_timestamp": alert.alert_history_timestamp.isoformat() if alert.alert_history_timestamp else None,
                "alert_history_read": alert.alert_history_read,
                "alert_history_read_at": alert.alert_history_read_at.isoformat() if alert.alert_history_read_at else None,
                "alert_history_alert_rule_id": alert.alert_history_alert_rule_id,
                "alert_history_context": alert.alert_history_context
            })

        return jsonify({
            "status": "success",
            "count": len(data),
            "data": data,
            "filters_applied": {
                "start_time": start_time_str,
                "end_time": end_time_str,
                "limit": limit,
                "offset": offset
            }
        }), 200

    except Exception as e:
        logger.error("Error in get_all_alert_history_web: %s", str(e), exc_info=Settings.EXEC_INFO_API)
        return jsonify({"status": "error", "error": "Internal server error", "details": str(e)}), 500

@alerts_bp.route('/history/unread', methods=['GET'])
def get_unread_alert_history():
    '''
    GET /api/v1/alerts/history/unread
    Returns history of all unread alerts.
    
    Query Parameters (all optional):
    - start_time: ISO format datetime string (e.g., 2023-10-27T10:00:00)
    - end_time: ISO format datetime string (e.g., 2023-10-28T10:00:00)
    - limit: integer, max number of records to return (e.g., 50)
    - offset: integer, number of records to skip for pagination (e.g., 0)
    '''
    try:
        start_time_str = request.args.get('start_time')
        end_time_str = request.args.get('end_time')
        limit_str = request.args.get('limit')
        offset_str = request.args.get('offset')

        start_time = None
        end_time = None
        limit = None
        offset = None

        if start_time_str:
            try:
                start_time = datetime.fromisoformat(start_time_str)
            except ValueError:
                return jsonify({"status": "error", "error": "Invalid start_time format. Use ISO format (e.g., 2023-10-27T10:00:00)"}), 400

        if end_time_str:
            try:
                end_time = datetime.fromisoformat(end_time_str)
            except ValueError:
                return jsonify({"status": "error", "error": "Invalid end_time format. Use ISO format (e.g., 2023-10-27T10:00:00)"}), 400

        if limit_str:
            try:
                limit = int(limit_str)
                if limit < 1:
                    return jsonify({"status": "error", "error": "Limit must be a positive integer"}), 400
            except ValueError:
                return jsonify({"status": "error", "error": "Invalid limit format. Must be an integer"}), 400

        if offset_str:
            try:
                offset = int(offset_str)
                if offset < 0:
                    return jsonify({"status": "error", "error": "Offset must be a non-negative integer"}), 400
            except ValueError:
                return jsonify({"status": "error", "error": "Invalid offset format. Must be an integer"}), 400

        results = get_all_alert_history(start_time, end_time, limit, offset, False)

        data = []
        for alert in results:
            data.append({
                "alert_history_id": alert.alert_history_id,
                "alert_history_timestamp": alert.alert_history_timestamp.isoformat() if alert.alert_history_timestamp else None,
                "alert_history_read": alert.alert_history_read,
                "alert_history_read_at": alert.alert_history_read_at.isoformat() if alert.alert_history_read_at else None,
                "alert_history_alert_rule_id": alert.alert_history_alert_rule_id,
                "alert_history_context": alert.alert_history_context
            })

        return jsonify({
            "status": "success",
            "count": len(data),
            "data": data,
            "filters_applied": {
                "start_time": start_time_str,
                "end_time": end_time_str,
                "limit": limit,
                "offset": offset
            }
        }), 200

    except Exception as e:
        logger.error("Error in get_unread_alert_history: %s", str(e), exc_info=Settings.EXEC_INFO_API)
        return jsonify({"status": "error", "error": "Internal server error", "details": str(e)}), 500

@alerts_bp.route('/history/<int:alert_history_id>/mark/read', methods=['POST'])
def mark_alert_history_read(alert_history_id: int):
    '''
    POST /api/v1/alerts/history/<alert_history_id:int>/mark/read
    Marks alert history with given id as read
    '''
    try:
        success = mark_alert_as_read(alert_history_id)

        if success:
            return jsonify({
                "status": "success"
            }), 200
        else:
            return jsonify({
                "status": "error",
                "message": f"Alert history with id {alert_history_id} not found"
            }), 404

    except Exception as e:
        logger.error("Error in mark_alert_history_read: %s", str(e), exc_info=Settings.EXEC_INFO_API)
        return jsonify({"status": "error", "error": "Internal server error", "details": str(e)}), 500

@alerts_bp.route('/history/<int:alert_history_id>/mark/unread', methods=['POST'])
def mark_alert_history_unread(alert_history_id: int):
    '''
    POST /api/v1/alerts/history/<alert_history_id:int>/mark/unread
    Marks alert history with given id as unread
    '''
    try:
        success = mark_alert_as_unread(alert_history_id)

        if success:
            return jsonify({
                "status": "success"
            }), 200
        else:
            return jsonify({
                "status": "error",
                "message": f"Alert history with id {alert_history_id} not found"
            }), 404

    except Exception as e:
        logger.error("Error in mark_alert_history_unread: %s", str(e), exc_info=Settings.EXEC_INFO_API)
        return jsonify({"status": "error", "error": "Internal server error", "details": str(e)}), 500

@alerts_bp.route('/rule/all', methods=['GET'])
def get_all_alert_rule_web():
    '''
    GET /api/v1/alerts/rule/all
    Returns all rules.
    '''

    try:
        results = get_all_alert_rule()

        data = []
        for rule in results:
            data.append({
                "alert_rule_id": rule.alert_rule_id,
                "alert_rule_timestamp": rule.alert_rule_timestamp,
                "alert_rule_name": rule.alert_rule_name,
                "alert_rule_description": rule.alert_rule_description,
                "alert_rule_params": rule.alert_rule_params,
                "alert_rule_enabled": rule.alert_rule_enabled
            })

        return jsonify({
            "status": "success",
            "count": len(data),
            "data": data
        }), 200

    except Exception as e:
        logger.error("Error in get_all_alert_rule_web: %s", e, exc_info=Settings.EXEC_INFO_API)
        return jsonify({"status": "error", "error": "Internal server error", "details": str(e)}), 500

@alerts_bp.route('/rule/add', methods=['POST'])
def add_alert_rule_web():
    '''
    POST /api/v1/alerts/rule/all
    Adds a new custom alert rule.
    
    Expected JSON payload for single rule:
    {
        "name": "name of alert",
        "description": "description of alert",
        "params": {
            "field": "speed",
            "operator": ">",
            "value": 10.0
        }
    }

    Expected JSON payload for multiple/combined rules:
    {
        "name": "name of alert",
        "description": "description of alert",
        "params": {
            "rules": [
                {
                    "field": "inside_geofence",
                    "value": true,
                    "operator": "=",
                    "valueGeofenceid": 3
                },
                {
                    "field": "enter_geofence",
                    "value": true,
                    "operator": "=",
                    "valueGeofenceid": 3
                },
                {
                    "field": "exit_geofence",
                    "value": true,
                    "operator": "=",
                    "valueGeofenceid": 3
                }
            ],
            "combinator": "or"
        }
    }
    '''
    data = None
    try:
        data = request.get_json()
        if not data:
            return jsonify({"status": "error", "error": "No JSON data provided"}), 400

        rule_name = data.get('name')
        rule_description = data.get('description', '')
        rule_params = data.get('params')

        if not rule_name:
            return jsonify({"status": "error", "error": "Missing required fields: 'name'"}), 400

        if rule_params is None:
            return jsonify({"status": "error", "error": "Missing required fields: 'params'"}), 400

        try:
            validated_params = RuleTreeAdapter.validate_python(rule_params)

            try:
                build_sqlalchemy_expression(validated_params)
            except ValueError as e:
                logger.warning("Invalid rule logic detected: %s", str(e))
                return jsonify({"status": "error", "error": "Invalid rule logic", "details": str(e)}), 400
            except Exception as e:
                logger.error("Unexpected error during rule validation: %s", str(e), exc_info=Settings.EXEC_INFO_API)
                return jsonify({"status": "error", "error": "Internal error during rule validation", "details": str(e)}), 500

            params_for_db = validated_params.model_dump()

        except Exception as e:
            logger.error("Validation failed for new rule params: %s", str(e))
            return jsonify({"status": "error", "error": "Invalid rule parameters", "details": str(e)}), 400

        new_rule_id = add_alert_rule_to_db(rule_name, rule_description, params_for_db)

        return jsonify({
            "status": "success",
            "message": "Alert rule created successfully",
            "alert_rule_id": new_rule_id
        }), 201

    except json.JSONDecodeError:
        return jsonify({"status": "error", "error": "Invalid JSON format"}), 400
    except Exception as e:
        logger.error("Error in add_alert_rule_web: %s", str(e), exc_info=Settings.EXEC_INFO_API)
        write_audit_log("Error adding alert rule", __name__, {"info": str(e), "payload": str(data)}, "ERROR")
        return jsonify({"status": "error", "error": "Internal server error", "details": str(e)}), 500

@alerts_bp.route('/rule/<int:alert_rule_id>/mark/disable', methods=['POST'])
def mark_alert_rule_disable(alert_rule_id: int):
    '''
    POST /api/v1/rule/<int:alert_rule_id>/disable
    Disables the selected alert rule
    '''
    try:
        success = mark_rule_as_disable(alert_rule_id)

        if success:
            return jsonify({
                "status": "success"
            }), 200
        else:
            return jsonify({
                "status": "error",
                "message": f"Rule with id {alert_rule_id} not found"
            }), 404

    except Exception as e:
        logger.error("Error in mark_alert_rule_disable: %s", str(e), exc_info=Settings.EXEC_INFO_API)
        return jsonify({"status": "error", "error": "Internal server error", "details": str(e)}), 500

@alerts_bp.route('/rule/<int:alert_rule_id>/mark/enable', methods=['POST'])
def mark_alert_rule_enable(alert_rule_id: int):
    '''
    POST /api/v1/rule/<int:alert_rule_id>/enable
    Enables the selected alert rule
    '''
    try:
        success = mark_rule_as_enable(alert_rule_id)

        if success:
            return jsonify({
                "status": "success"
            }), 200
        else:
            return jsonify({
                "status": "error",
                "message": f"Rule with id {alert_rule_id} not found"
            }), 404

    except Exception as e:
        logger.error("Error in mark_alert_rule_enable: %s", str(e), exc_info=Settings.EXEC_INFO_API)
        return jsonify({"status": "error", "error": "Internal server error", "details": str(e)}), 500

@alerts_bp.route('/rule/<int:alert_rule_id>/update', methods=['POST', 'PATCH'])
def update_alert_rule_web(alert_rule_id: int):
    '''
    POST/PATCH/PUT /api/v1/alerts/rule/<int:alert_rule_id>/update
    Updates an existing alert rule. Supports partial updates.

    Expects JSON payload
    {
        "name": "new name of alert",
        "description": "new description of alert",
        "params": { ... }
    }
    '''
    if alert_rule_id == 1 or alert_rule_id == 2:
            return jsonify({"error": "Forbidden."}), 403
    
    data = None
    try:
        data = request.get_json()

        if data is None:
            return jsonify({"status": "error", "error": "No JSON data provided"}), 400

        name = data.get('name')
        desc = data.get('description')
        params = data.get('params')

        if not any([name, desc, params]):
            return jsonify({"status": "error", "error": "At least one field ('name', 'description', or 'params') must be provided to update."}), 400

        params_for_db = None

        if params is not None:
            try:
                validated_params = RuleTreeAdapter.validate_python(params)

                try:
                    build_sqlalchemy_expression(validated_params)
                except ValueError as e:
                    logger.warning("Invalid rule logic detected during update: %s", str(e))
                    return jsonify({"status": "error", "error": "Invalid rule logic", "details": str(e)}), 400
                except Exception as e:
                    logger.error("Unexpected error during rule validation: %s", str(e), exc_info=Settings.EXEC_INFO_API)
                    return jsonify({"status": "error", "error": "Internal error during rule validation", "details": str(e)}), 500

                params_for_db = validated_params.model_dump()

            except Exception as e:
                logger.error("Validation failed for updated rule params: %s", str(e))
                return jsonify({"status": "error", "error": "Invalid rule parameters", "details": str(e)}), 400

        try:
            success = update_alert_rule_in_db(
                alert_rule_id=alert_rule_id,
                name=name,
                desc=desc,
                params=params_for_db
            )
        except ValueError as ve:
            return jsonify({"status": "error", "error": str(ve)}), 400

        if not success:
            return jsonify({"status": "error", "message": f"Alert rule with id {alert_rule_id} not found."}), 404

        return jsonify({
            "status": "success",
            "message": "Alert rule updated successfully",
            "alert_rule_id": alert_rule_id
        }), 200

    except json.JSONDecodeError:
        return jsonify({"status": "error", "error": "Invalid JSON format"}), 400
    except Exception as e:
        logger.error("Error in update_alert_rule_web: %s", str(e), exc_info=Settings.EXEC_INFO_API)
        write_audit_log("Error updating alert rule", __name__, {"info": str(e), "payload": str(data), "rule_id": alert_rule_id}, "ERROR")
        return jsonify({"status": "error", "error": "Internal server error", "details": str(e)}), 500

@alerts_bp.route('/rule/<int:alert_rule_id>/delete', methods=['DELETE'])
def delete_alert_rule_by_id_web(alert_rule_id):
    '''
    DELETE /api/v1/alerts/rule/<alert_rule_id>/delete
    Deletes an existing Area of Interest.

    Query Param:
    - alert_rule_name: str (Name of alert rule to be deleted, so that users can't spam through alert_rule_ids and accidentally delete)
    '''
    try:
        alert_rule_name = request.args.get("alert_rule_name")

        if alert_rule_id == 1 or alert_rule_id == 2:
            return jsonify({"error": "Forbidden."}), 403

        if not alert_rule_name:
            return jsonify({"error": "Missing required query parameter: 'alert_rule_name'."}), 400

        alert_rule = get_alert_rule_by_id(alert_rule_id)
        if not alert_rule:
            return jsonify({"error": f"Alert rule with ID {alert_rule_id} not found."}), 404

        if alert_rule.alert_rule_name != alert_rule_name:
            return jsonify({"error": "'alert_rule_name' does not match the Alert rule with the given ID."}), 403

        delete_alert_rule_in_db(alert_rule_id)

        checkalert_rule = get_alert_rule_by_id(alert_rule_id)
        if not checkalert_rule:
            return jsonify({
                "status": "success", 
                "message": f"Alert rule '{alert_rule_name}' (ID: {alert_rule_id}) deleted successfully."
            }), 200
        else:
            logger.error("Failed to delete Alert rule with ID %d. User provided %s", alert_rule_id, str(request.args.get("alert_rule_name")))
            return jsonify({"error": "Internal server error: Failed to delete Alert rule."}), 500

    except Exception as e:
        logger.error("Error in delete_alert_rule_by_id_web: %s", str(e), exc_info=Settings.EXEC_INFO_API)
        write_audit_log("Error in delete_alert_rule_by_id_web", __name__, {"alert_rule_id": alert_rule_id, "info": str(e)}, "ERROR")

        return jsonify({"error": "Internal server error"}), 500

@alerts_bp.route('/rescan', methods=['POST'])
def rescan_alerts():
    '''
    POST /api/v1/alerts/rescan
    Force rescan of all rules for vessel locations within the past n minutes.

    Request body:
    n: int, number of minutes
    '''
    try:
        n = request.form.get("n")
        if not n or not str(n).isdigit():
            return jsonify({"status": "error", "error": "Integer n is required."}), 400
        thread = threading.Thread(target=check_all_vessels, args=(int(n),))
        thread.start()
        return jsonify({"status": "success"}), 202

    except Exception as e:
        logger.error("Error in rescan_alerts: %s", str(e), exc_info=Settings.EXEC_INFO_API)
        return jsonify({"status": "error", "error": "Internal server error", "details": str(e)}), 500
